(()=>{
const $=(sel,root=document)=>root.querySelector(sel); const content=window.EE_CONTENT||{players:[],staff:[]};
const safe=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const resolveAsset = p => {if (!p) return ''; const value=String(p).trim(); if (/^(https?:\/\/|assets\/|\.\/)/i.test(value) && !/^javascript:/i.test(value)) return value; return '';};
const playerGrid=$('#player-grid'); const players=(content.players||[]).slice(0,4);
playerGrid.innerHTML=players.map((p,i)=>`<button type="button" class="player-card reveal" data-player="${i}" aria-label="Open trailer for ${safe(p.name)}">${resolveAsset(p.image)?`<img class="player-portrait" src="${safe(resolveAsset(p.image))}" alt="${safe(p.name)}">`:`<span class="player-arch"></span><img class="player-watermark" src="exalted-era-logo.png" alt="">`}<span class="player-card-number">0${i+1} / THE CIRCLE</span><span class="player-card-status">${safe(p.status||'COMING SOON')}</span><span class="player-card-content"><span class="player-card-kicker">${safe(p.title||'THE ASCENSION')}</span><strong class="player-card-title">${safe(p.name||'TO BE REVEALED')}</strong><span class="player-card-action"><span>${resolveAsset(p.video)?'WATCH REVEAL TRAILER':'TRAILER COMING SOON'}</span><span class="player-play">▶</span></span></span></button>`).join('');
const staffGrid=$('#staff-grid'); staffGrid.innerHTML=(content.staff||[]).map((person,i)=>`<article class="staff-card reveal"><div class="staff-photo">${resolveAsset(person.image)?`<img src="${safe(resolveAsset(person.image))}" alt="Portrait of ${safe(person.name)}" loading="lazy">`:`<span class="staff-placeholder">${String(i+1).padStart(2,'0')}</span>`}</div><div class="staff-meta"><span class="staff-index">THE PEOPLE / 0${i+1}</span><h3>${safe(person.name||'TO BE ANNOUNCED')}</h3><span class="staff-role">${safe(person.role||'STAFF')}</span><p class="staff-bio">${safe(person.bio||'')}</p>${resolveAsset(person.social)?`<a class="staff-social" target="_blank" rel="noopener noreferrer" href="${safe(resolveAsset(person.social))}">CONNECT ↗</a>`:''}</div></article>`).join('');
const dialog=$('#video-dialog'),videoContent=$('#video-dialog-content'); const closeVideo=()=>{dialog.close();videoContent.replaceChildren()};
$('#close-video').addEventListener('click',closeVideo);dialog.addEventListener('click',e=>{if(e.target===dialog)closeVideo()});
playerGrid.addEventListener('click',e=>{const card=e.target.closest('[data-player]');if(!card)return;const p=players[+card.dataset.player];if(!p)return;const v=resolveAsset(p.video);videoContent.replaceChildren();if(!v){videoContent.innerHTML='<div class="empty-video"><img src="exalted-era-logo.png" alt=""><h3>REVEAL COMING SOON.</h3><p>THIS PLAYER\'S TRAILER WILL PREMIERE HERE.</p></div>';}else if(/youtube\.com|youtu\.be/i.test(v)){let id='';try{const url=new URL(v);id=url.hostname.includes('youtu.be')?url.pathname.split('/')[1]:url.searchParams.get('v')||(url.pathname.match(/\/embed\/([^/]+)/)||[])[1]||'';}catch{}if(/^[A-Za-z0-9_-]{11}$/.test(id)){const f=document.createElement('iframe');f.src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`;f.title=`${p.name} trailer`;f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';f.referrerPolicy='strict-origin-when-cross-origin';f.allowFullscreen=true;videoContent.appendChild(f);}else{videoContent.textContent='Invalid YouTube video URL. Check content.js.';}}else{const el=document.createElement('video');el.src=v;el.controls=true;el.autoplay=true;el.playsInline=true;videoContent.appendChild(el)}dialog.showModal();});
const apply=$('#application-link');if(content.applicationUrl){const v=resolveAsset(content.applicationUrl);if(v){apply.href=v;$('.small-disclaimer')?.remove();}}
const menu=$('#menu-toggle'),links=$('#mobile-links');menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const header=$('#site-header'),progress=$('#progress');let ticking=false;function updateScroll(){const total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(total>0?Math.max(0,scrollY/total*100):0)+'%';header.classList.toggle('scrolled',scrollY>15);ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScroll);ticking=true}},{passive:true});updateScroll();$('#year').textContent=new Date().getFullYear();
if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -30px 0px'});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));}
})();
